set(PROJECT_INCLUDE_DIRS /home/florian/programmes/swiftsim/logger)
set(PROJECT_LIBRARIES -llogger)

set(HDF5_INCLUDE_DIR $ENV{HDF5_INCLUDE_DIR})
set(HDF5_LIBRARIES $ENV{HDF5_LIBRARIES})
#if((NOT DEFINED HDF5_INCLUDE_DIR) OR (NOT DEFINED HDF5_LIBRARIES))
		find_package(HDF5 REQUIRED)
#endif()


set(PROJECT_INCLUDE_DIRS ${PROJECT_INCLUDE_DIRS} ${HDF5_INCLUDE_DIR})
set(PROJECT_LIBRARIES ${PROJECT_LIBRARIES} ${HDF5_LIBRARIES})

message(STATUS "INC : ${PROJECT_INCLUDE_DIRS}")
message(STATUS "LIB : ${PROJECT_LIBRARIES}")
